---
title: "California Wildfires"
author: "Lillian and Ainsley"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(readxl)

counties <- read_csv( "California_Counties_-3636863462195930370.csv", show_col_types = FALSE )

california <- read_csv("https://hub.arcgis.com/api/v3/datasets/c3c10388e3b24cec8a954ba10458039d_0/downloads/data?format=csv&spatialRefId=3857&where=1%3D1")


```


# Simulated Data 

```{r}
simulated_risk <- tibble(county = counties$`County Name`,
                         risk = runif(n = 58, min = 0, max = 100))

view(simulated_risk)

```

# Wildfire Perimeter Map
```{r}

library(tidyverse)
library(sf)
library(tmap)
library(geojsonsf)

fires <- geojson_sf("California_Fire_Perimeters_(1950%2B).geojson" )

recent_fires <- fires |>
  filter( YEAR_ == 2020 )

US <- gadm("USA", level = 2, path = getwd())
CA <- US[US$NAME_1 == "California", ]
CA <- st_as_sf(CA)

tmap_options( basemap.server = "USGS")
tmap_mode( "view" )


tm_shape(CA) + tm_polygons(fill= "grey", col = "white")+
  
 tm_shape( recent_fires ) +
  tm_polygons( id = "FIRE_NAME", fill = "firebrick")

```

# Precipitation Graph
```{r}
library(readxl)
library(tidyverse)
library(geodata)
library(sf)
library(tmap)
precipitation_data <- read_excel("california_precipitation 1.xlsx") 
precipitation_data <- precipitation_data |>
  mutate( Name = sub( pattern = " County", replacement = "", x = Name, fixed =TRUE ))

yearly_avg_precipitation <- precipitation_data |>
group_by(Name, Year) |>
  summarize(avg_precip=mean(Precipitation))

ggplot(yearly_avg_precipitation)+
  geom_line(aes(x=Year, y=avg_precip, color=Name))+
  theme_bw(base_size = 12)+
  theme(legend.position="none") +
  expand_limits(y=0) +
  labs(x="Years", y="Average Precipitation", title= "Avg.Precipitation for California Counties from 2015-2024")
```

# Precipitation Map
```{r}


ca_2020_precip <- yearly_avg_precipitation |> 
  filter( Year == 2020 )

US <- gadm("USA", level = 2, path = getwd())
CA <- US[US$NAME_1 == "California", ]
CA <- st_as_sf(CA)

ca_precip_map <- CA |>
  left_join(ca_2020_precip, by = c("NAME_2" = "Name"))

tmap_options(basemap.server="OpenStreetMap")
tmap_mode("view")

tm_shape(ca_precip_map) + 
  tm_polygons( fill = "avg_precip", palette = "Blues", 
              id = "NAME_2", title = "Avg Precipitation (2020)") +
  tm_layout(title = "California County Precipitation - 2020")

```

# Temperature Graph
```{r}
temperature_data <- read_csv("california_temperature.csv")


temperature_data <- temperature_data |>
  mutate( Name = sub( pattern = " County", replacement = "", x = Name, fixed =TRUE ))

yearly_avg_temperature <- temperature_data |>
group_by(Name, Year) |>
  summarize(avg_temp=mean(Temperature))

ggplot(yearly_avg_temperature)+
  geom_line(aes(x=Year, y=avg_temp, color=Name))+
  theme_bw(base_size = 12)+
  theme(legend.position="none") +
  expand_limits(y=0) +
  labs(x="Years", y="Average Temperature", title= "Avg.Precipitation for California Counties from 2015-2024")
```

# Temperature Map
```{r}
ca_2020_temp <- yearly_avg_temperature |> 
  filter( Year == 2020 )

US <- gadm("USA", level = 2, path = getwd())
CA <- US[US$NAME_1 == "California", ]
CA <- st_as_sf(CA)

ca_temp_map <- CA |>
  left_join(ca_2020_temp, by = c("NAME_2" = "Name"))

tmap_options(basemap.server="OpenStreetMap")
tmap_mode("view")

tm_shape(ca_temp_map) + 
  tm_polygons( fill = "avg_temp", palette = "Blues", 
              id = "NAME_2", title = "Avg temperature (2020)") +
  tm_layout(title = "California County Temperature- 2020")


```


# Summary Stats- 2020 Temperature
```{r}
library(tinytable)
library(tidyverse)
temp_summary <- ca_2020_temp |>
  ungroup() |>
  summarize( "Average temperature" = mean( avg_temp ),
             "Median temperature" = median( avg_temp))



#make a table
#tt(temp_summary) 

```

# 2020 Precipitation
```{r}
precip_summary <- ca_2020_precip |>
ungroup() |>
  summarize( "Average precipitation" = mean( avg_precip ),
             "Median precipitation" = median( avg_precip))


#make a table
#tt(temp_summary) 
##2020
precip_summary <- ca_2020_precip |>
ungroup() |>
  summarize( "Average precipitation" = mean( avg_precip ),
             "Median precipitation" = median( avg_precip))


#make a table
#tt(precip_summary)

#summary_stats <- 
  #//bind_cols(temp_summary, precip_summary)
#//tt(summary_stats, digits = 3)
```

# 2021 Temperatures And Precipitation
```{r}
library(tinytable)
library(tidyverse)

ca_2021_temp <- yearly_avg_temperature |> 
  filter( Year == 2021 )
ca_2021_precip <- yearly_avg_precipitation |> 
  filter( Year == 2021 )

temp_summary21 <- ca_2021_temp |>
  ungroup() |>
  summarize( "Average temperature" = mean( avg_temp ),
             "Median temperature" = median( avg_temp))

#make a table
#tt(temp_summary21) 

ca_2021_precip <- yearly_avg_precipitation |> 
  filter( Year == 2021 )

precip_summary21 <- ca_2021_precip |>
  ungroup() |>
  summarize( "Average precipitation" = mean( avg_precip ),
             "Median precipitation" = median( avg_precip))

#make a table
#tt(precip_summary21) 

```

# 2022 Temperatures And Precipitation
```{r}
library(tinytable)
library(tidyverse)

ca_2022_temp <- yearly_avg_temperature |> 
  filter( Year == 2022 )
ca_2022_precip <- yearly_avg_precipitation |> 
  filter( Year == 2022 )

temp_summary22 <- ca_2022_temp |>
  ungroup() |>
  summarize( "Average temperature" = mean( avg_temp ),
             "Median temperature" = median( avg_temp))

#make a table
#tt(temp_summary22) 

ca_2022_precip <- yearly_avg_precipitation |> 
  filter( Year == 2022 )

precip_summary22 <- ca_2022_precip |>
  ungroup() |>
  summarize( "Average precipitation" = mean( avg_precip ),
             "Median precipitation" = median( avg_precip))

#make a table
#tt(precip_summary22) 

```

# 2023 Temperatures And Precipitation
```{r}
library(tinytable)
library(tidyverse)

ca_2023_temp <- yearly_avg_temperature |> 
  filter( Year == 2023 )
ca_2023_precip <- yearly_avg_precipitation |> 
  filter( Year == 2023 )

temp_summary23 <- ca_2023_temp |>
  ungroup() |>
  summarize( "Average temperature" = mean( avg_temp ),
             "Median temperature" = median( avg_temp))

#make a table
#tt(temp_summary23) 

ca_2023_precip <- yearly_avg_precipitation |> 
  filter( Year == 2023 )

precip_summary23 <- ca_2023_precip |>
  ungroup() |>
  summarize( "Average precipitation" = mean( avg_precip ),
             "Median precipitation" = median( avg_precip))

#make a table
#tt(precip_summary23) 

```

# 2024 Temperatures And Precipitation
```{r}
library(tinytable)
library(tidyverse)

ca_2024_temp <- yearly_avg_temperature |> 
  filter( Year == 2024 )
ca_2024_precip <- yearly_avg_precipitation |> 
  filter( Year == 2024 )

temp_summary24 <- ca_2024_temp |>
  ungroup() |>
  summarize( "Average temperature" = mean( avg_temp ),
             "Median temperature" = median( avg_temp))

#make a table
#tt(temp_summary24) 

ca_2024_precip <- yearly_avg_precipitation |> 
  filter( Year == 2024 )

precip_summary24 <- ca_2024_precip |>
  ungroup() |>
  summarize( "Average precipitation" = mean( avg_precip ),
             "Median precipitation" = median( avg_precip))

#make a table
#tt(precip_summary24) 

```


```{r}
years <- c(2020,2021,2022,2023,2024)

summary_statstemp <- 
  bind_rows(temp_summary, temp_summary21, temp_summary22,temp_summary23,temp_summary24) |>
  bind_cols(years) 

tt(summary_statstemp)

names( summary_statstemp ) <- c( "Average Temperature", "Median Temperature", "Year")

summary_statsprecip <- 
  bind_rows(precip_summary, precip_summary21, precip_summary22,precip_summary23,precip_summary24) |>  bind_cols(years)

tt(summary_statsprecip)

names( summary_statsprecip ) <- c( "Average Precipitation", "Median Precipitation", "Year")

ggplot(summary_statstemp)+
  geom_line(aes(x=Year, y=`Average Temperature`))+
  theme_bw(base_size = 12)+
  theme(legend.position="none") +
  expand_limits(y=0) +
  labs(x="Years", y="Average Temperature (degrees F)", title= "Avg.Temperature for California from 2020-2024")

ggplot(summary_statsprecip)+
  geom_line(aes(x=Year, y=`Average Precipitation`))+
  theme_bw(base_size = 12)+
  theme(legend.position="none") +
  expand_limits(y=0) +
  labs(x="Years", y="Average Precipitation (in.)", title= "Avg.Precipitation for California from 2020-2024")



```

