---
title: "California Wildfires"
author: "Lillian and Ainsley"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(readxl)

counties <- read_csv( "California_Counties_-3636863462195930370.csv", show_col_types = FALSE )

california <- read_csv("https://hub.arcgis.com/api/v3/datasets/c3c10388e3b24cec8a954ba10458039d_0/downloads/data?format=csv&spatialRefId=3857&where=1%3D1")


```


# Simulated Data 

```{r}
simulated_risk <- tibble(county = counties$`County Name`,
                         risk = runif(n = 58, min = 0, max = 100))

view(simulated_risk)

```

# Wildfire Perimeter Map
```{r}

library(tidyverse)
library(sf)
library(tmap)
library(geojsonsf)



fires <- geojson_sf("California_Fire_Perimeters_(1950%2B).geojson" )

recent_fires <- fires |>
  filter( YEAR_ == 2020 )

tmap_options( basemap.server = "USGS")
tmap_mode( "view" )
tm_shape( recent_fires ) +
  tm_polygons( id = "FIRE_NAME", fill = "firebrick")

```

# Precipitation Graph
```{r}
library(readxl)
precipitation_data <- read_excel("california_precipitation 1.xlsx")

yearly_avg_precipitation <- precipitation_data |>
group_by(Name, Year) |>
  summarize(avg_precip=mean(Precipitation))

ggplot(yearly_avg_precipitation)+
  geom_line(aes(x=Year, y=avg_precip, color=Name))+
  theme_bw(base_size = 12)+
  theme(legend.position="none") +
  expand_limits(y=0) +
  labs(x="Years", y="Average Precipitation", title= "Avg.Precipitation for California Counties from 2015-2024")

```
